<br><br>

<font color=#191347 ><font>
<p style = "font-family:times;">
    <font size="7">
        Interactive Learning 
    </font>    
</p>

<br>
    
<font color=#ed1c24><font>
<p style = "font-family:optima;">
    <font size="6">
        Homework #3
    </font>    
<font color=#000000> <font>
</p>

> $\textit{Mohammad Saadati - 810198410}$

# Table of Contents

- [Packages](#0)
- [Problem 2](#1)
    - [Question 1](#1-1)
    - [Question 2](#1-2)
    - [Question 3](#1-3)
    - [Question 4](#1-4)
- [Problem 3](#2)
    - [َPart 1](#2-1)
        - [Value Iteration](#2-1-1)
        - [Policy Iteration](#2-1-2)
    - [Part 2](#2-2)
        - [Value Iteration](#2-2-1)
        - [Policy Iteration](#2-2-2)
    - [Part 3](#2-3)
        - [A](#2-3-1)
        - [B](#2-3-2)

<a name='0'></a>
## Packages

Run the following cell to load the packages you'll need.

In [1]:
import numpy as np
import itertools
from gym import Env

from env import FrozenLake
from env import make_map

# Action Space 
LEFT = 0
DOWN = 1
RIGHT = 2
UP = 3
X = 0
Y = 1

ACTION_SPACE = [LEFT,DOWN,RIGHT,UP]
ACTIONS_NAMES = ["←","↓","→","↑"]

Discount = 0.9
Sd_number = 810198410

<a name='1'></a>
# Problem 2

<a name='1-1'></a>
## Question 1

<a name='1-2'></a>
## Question 2

<a name='1-3'></a>
## Question 3

<a name='1-4'></a>
## Question 4

<a name='2'></a>
# Problem 3

In [2]:
def show_states_value_on_map(states_value, map_size):
    environment_map = ""
    for i in range(map_size):
        environment_map += ("\n"+ int(10*map_size)*"-" + "\n| ")
        for j in range(map_size):
            environment_map += "{:.4f} | ".format(states_value[i,j])           
    environment_map += ("\n" + int(10*map_size)*"-")
    return environment_map

def show_actions_on_map(value_iteration, map_size):
    environment_map = ""
    for i in range(map_size):
        environment_map += ("\n"+ int(4.3*map_size)*"-" + "\n| ")
        for j in range(map_size):
            if (i,j)!=(map_size-1,map_size-1):
                environment_map += "{D} | ".format(D=ACTIONS_NAMES[value_iteration.get_optimal_policy([i, j])])
            else:
                environment_map += "* | "          
    environment_map += ("\n" + int(4.3*map_size)*"-")
    return environment_map

<a name='2-1'></a>
## Part 1

In [3]:
MAP_SIZE = 6
BREAKING_PROBABILITY = 0.0001

environment = FrozenLake(studentNum=Sd_number)

environment.render()


-------------------------------------------------------
| 0.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 
-------------------------------------------------------
| 0.0001 | 0.0001 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 
-------------------------------------------------------
| 1.0000 | 0.0001 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 
-------------------------------------------------------
| 1.0000 | 0.0001 | 0.0001 | 0.0001 | 0.0001 | 0.0001 | 
-------------------------------------------------------
| 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 0.0001 | 
-------------------------------------------------------
| 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 0.0000 | 
-------------------------------------------------------


<a name='2-1-1'></a>
### Value Iteration

In [4]:
class ValueIteration():
    def __init__(self, env, discount, theta, map_size):
        self.env = env
        self.discount = discount
        self.theta = theta
        self.map_size = map_size
        self.delta = 0
        self.state_values = np.zeros((self.map_size,self.map_size))
        self.q_values = np.zeros((self.map_size,self.map_size,4))
    
    def value_estimation(self):
        self.delta = np.inf
        
        while(self.delta > self.theta):
            
            self.delta = 0
            
            for state in itertools.product(range(self.map_size), range(self.map_size)):
                if (state[X],state[Y]) == (self.map_size-1,self.map_size-1):
                    continue
                    
                for action in ACTION_SPACE:
                    next_states, states_probability, breaking_possibility, is_end = self.env.find_next_states(action=action, current_state=(state[X],state[Y]))
                    reward = np.where(is_end, 99, ((1-breaking_possibility) * -1) + (breaking_possibility * -11))
                    next_states = np.array(next_states)
                    self.q_values[state[X],state[Y],action] = np.sum(states_probability*(reward+self.discount*self.state_values[next_states[:,0], next_states[:,1]]))
    
                v = self.state_values[state[X],state[Y]]

                self.state_values[state[X],state[Y]] = np.max(self.q_values[state[X],state[Y],:])

                self.delta = np.max([self.delta, abs(v - self.state_values[state[X],state[Y]])])
    
    def get_optimal_policy(self, state):
        return np.argmax(self.q_values[state[X],state[Y],:])
    
    def get_state_values(self):
        return self.state_values
    
    def get_q_values(self):
        return self.q_values

In [5]:
value_iteration = ValueIteration(FrozenLake(studentNum=Sd_number), Discount, 1e-8, MAP_SIZE)
value_iteration.value_estimation()

print("states value :\n", show_states_value_on_map(value_iteration.get_state_values(), MAP_SIZE))

states value :
 
------------------------------------------------------------
| 26.1929 | 30.0812 | 17.3231 | 22.7638 | 29.6611 | 36.8419 | 
------------------------------------------------------------
| 30.6258 | 35.6471 | 31.9859 | 38.4259 | 46.1634 | 54.3519 | 
------------------------------------------------------------
| 35.9200 | 41.8198 | 48.6298 | 56.2760 | 64.9640 | 74.3257 | 
------------------------------------------------------------
| 41.3085 | 48.5310 | 56.3703 | 65.1780 | 74.9210 | 85.6277 | 
------------------------------------------------------------
| 25.6742 | 41.4664 | 48.9862 | 64.8993 | 85.4633 | 97.6371 | 
------------------------------------------------------------
| 21.5512 | 37.0133 | 54.6250 | 74.5789 | 97.0272 | 0.0000 | 
------------------------------------------------------------


In [6]:
print("state-action value : \n\n", value_iteration.get_q_values())

state-action value : 

 [[[22.52333384 26.19285648 16.54290946 22.52333384]
  [22.25406176 30.08123284  5.70989766 16.27363738]
  [15.74603334 17.32309307  9.68720736  5.18229361]
  [ 5.29065143 22.76381015 15.50649154  9.79556517]
  [10.28617933 29.66106422 21.94287664 15.99710569]
  [16.39790527 36.841947   22.34367621 22.34367621]]

 [[26.46810978 21.65264356 30.62575822 22.79858714]
  [26.37839636 35.64707276 18.30550907 16.72844934]
  [30.43530202 31.98589435 23.53712556  6.06396684]
  [18.31372514 38.42594177 30.05272431 10.67783942]
  [24.18993242 46.16342959 37.37665554 16.9326138 ]
  [31.03361312 54.35193588 37.81369633 23.31542554]]

 [[21.83583513 26.29756297 35.91997776 26.65130135]
  [22.1788024  41.81981185 32.70250939 31.15191706]
  [36.58198018 48.62976881 39.35263313 19.2404165 ]
  [33.37498722 56.27601106 46.89971561 24.92621844]
  [40.32686655 64.96398184 55.27197185 31.95364909]
  [48.01700414 74.32565515 55.76846965 39.23023009]]

 [[26.12925635 13.18402328 41.3085

In [7]:
print("optimal policy :\n", show_actions_on_map(value_iteration, MAP_SIZE))

optimal policy :
 
-------------------------
| ↓ | ↓ | ↓ | ↓ | ↓ | ↓ | 
-------------------------
| → | ↓ | ↓ | ↓ | ↓ | ↓ | 
-------------------------
| → | ↓ | ↓ | ↓ | ↓ | ↓ | 
-------------------------
| → | → | → | → | → | ↓ | 
-------------------------
| → | ↑ | ↑ | → | → | ↓ | 
-------------------------
| → | → | → | → | → | * | 
-------------------------


<a name='2-1-2'></a>
### Policy Iteration

<a name='2-2'></a>
## Part 2

<a name='2-2-1'></a>
### Value Iteration

<a name='2-2-2'></a>
### Policy Iteration

<a name='2-3'></a>
## Part 3

<a name='2-3-1'></a>
### A

<a name='2-3-2'></a>
### B